name: app
description: ""

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.4
  intl: ^0.19.0
  easy_date_timeline: ^1.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/images/

  fonts:
    - family: BrunoAce
      fonts:
        - asset: assets/fonts/BrunoAceSC-Regular.ttf
    - family: IrishGrover
      fonts:
        - asset: assets/fonts/IrishGrover-Regular.ttf
    - family: Play
      fonts: 
        - asset: assets/fonts/Play-Regular.ttf
        - asset: assets/fonts/Play-Bold.ttf
          weight: 700

  uses-material-design: true

