name: app
description: ""

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: any
  easy_date_timeline: ^2.0.0
  provider: ^6.1.2
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  path_provider: ^2.1.4
  firebase_app_check: ^0.3.1
  extended_image: ^9.0.4
  email_validator: ^3.0.0
  another_flutter_splash_screen: ^1.2.1
  flutter_launcher_icons: ^0.14.1
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: '^7.1.1'
  image: ^4.3.0
  firebase_messaging: ^15.1.6
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#17A990"
  adaptive_icon_foreground: "assets/images/icon-adaptive.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.25.7
  mockito: ^5.4.4
  build_runner: ^2.4.9
  fake_cloud_firestore: ^3.0.3
  
flutter:

  assets:
    - assets/images/

  fonts:
    - family: BrunoAce
      fonts:
        - asset: assets/fonts/BrunoAceSC-Regular.ttf
    - family: IrishGrover
      fonts:
        - asset: assets/fonts/IrishGrover-Regular.ttf
    - family: Play
      fonts: 
        - asset: assets/fonts/Play-Regular.ttf
        - asset: assets/fonts/Play-Bold.ttf
          weight: 700

  uses-material-design: true

