name: app
description: ""

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.4
  intl: ^0.19.0
  easy_date_timeline: ^1.1.3
  provider: ^6.1.2
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/images/

  fonts:
    - family: BrunoAce
      fonts:
        - asset: assets/fonts/BrunoAceSC-Regular.ttf
    - family: IrishGrover
      fonts:
        - asset: assets/fonts/IrishGrover-Regular.ttf
    - family: Play
      fonts: 
        - asset: assets/fonts/Play-Regular.ttf
        - asset: assets/fonts/Play-Bold.ttf
          weight: 700

  uses-material-design: true

